### ISSUE TITLE
Market decisions through delegated representation

### ISSUE THREAD

**Issue by ReidWilliams** [computablelabs/compspec#8]
From v0.3 of the protocol spec:

_Major decisions in the Market are made by token holder vote...A threshold `T_council` will be imposed, and only `MarketToken` holders who hold more than `T_council` units of `MarketToken` will be allowed to vote._

Qualitatively, this creates two mechanisms for making decisions. When `T_council` is 0, the market functions like a direct democracy with all token holders able to cast decision making votes. When `T_council` > 0, the market functions like a private company with a class of active shareholders with decision making power and a class of passive shareholders without decision making power. The only mechanism to transition from passive to active is by increasing token ownership.

Some markets may benefit from a decision making system analogous to public companies and representative democracies, where decision making power is reversably pooled by token holders to rest in a small set of individuals who make decisions and are accountable to their token-holding "constituents". This "elected" group would be akin to a board of directors or legislature.

Such a scheme may be useful in markets with long tails of ownership (perhaps through long tails of crowdsourced data contribution) and / or diverse demand-side uses where a diverse and potentially competing set of goals for the data market co-exist.

Such a scheme may also be a powerful proposition to crowdsourcing data listers who desire equity and decision making power in proposition to token ownership but do not want to or does not have the ability to vote on every decision individually.

An example implementation could involve minting a token tuple `(e, v)` where the `e` token is held as ownership stake / equity, and the `v` token is used for voting. The `v` token can be reversibly lent to another address to allow that address to vote as a proxy.

**Comment by rbharath** [comment]
Closing this issue since the discussion refers to an earlier protocol version and `T_council` no longer exists directly.
