### ISSUE TITLE
Council members can potentially gain more than one vote

### ISSUE THREAD

**Issue by ReidWilliams** [computablelabs/compspec#9]
From the protocol:

> The votes here are not stake-weighted. All council members have precisely one vote. So a council member with 5\*T_council and another council member with 1.1\*T_council MarketTokens have the same voting power.

This allows for a sybil style attack where a council member with `5.5*T_council` tokens distributes them to 5 separate addresses each with `1.1*T_council` tokens and gains 5 votes in the council.

**Comment by rbharath** [comment]
Slightly out of date, since the current vote staking mechanism just allows this council member to vote 5 times directly. This is documented in the book already, so closing for cleanup.
